package com.longhike.mapreduce;

public class Sources {
  public static final String[] texts = {
    "walking through the forest yesterday i noticed how the leaves crunched beneath my feet making"
        + " sounds like tiny firecrackers going off in slow motion the trees towered above me their"
        + " branches reaching toward a sky that seemed impossibly blue for october the air smelled"
        + " of pine needles and something else i couldnt quite identify maybe it was the scent of"
        + " time itself or perhaps just the decomposing matter that feeds the soil beneath the"
        + " forest floor squirrels darted between the oak trees carrying acorns in their cheeks"
        + " preparing for winter while somewhere in the distance a woodpecker hammered against dead"
        + " bark searching for insects or maybe just announcing its presence to the world i found"
        + " myself thinking about how different this place must have looked a hundred years ago"
        + " when loggers first came through cutting down the massive trees that had stood here for"
        + " centuries now second growth trees fill the spaces where giants once lived their smaller"
        + " trunks and younger bark telling a story of renewal and resilience that speaks to"
        + " something deep in the human spirit about our ability to recover from devastation and"
        + " loss the path i followed had been worn smooth by countless hikers and their dogs each"
        + " footstep adding to the collective memory embedded in the earth itself leading me deeper"
        + " into a wilderness that exists just outside the boundaries of suburban development where"
        + " houses and shopping centers wait patiently for their turn to expand into these"
        + " remaining pockets of nature\n",
    "the coffee shop on fifth street has become my second home over the past three months ever"
        + " since i started working remotely and discovered that my apartment walls were closing in"
        + " on me like a slow moving vise the baristas know my order now which is both comforting"
        + " and slightly embarrassing since it means i spend too much time here nursing the same"
        + " cup of dark roast for hours while pretending to work on my laptop but really just"
        + " watching people come and go through the glass doors that never seem to stop moving"
        + " students rush in between classes clutching textbooks and looking perpetually exhausted"
        + " business people tap their feet impatiently while waiting for complicated drinks with"
        + " names that sound more like chemistry experiments than beverages elderly couples sit at"
        + " corner tables sharing newspapers and comfortable silences that speak of decades spent"
        + " learning each others rhythms and preferences the background music shifts from jazz to"
        + " indie rock to something that might be described as atmospheric depending on who is"
        + " working behind the counter today and whether they prefer their workplace soundtrack to"
        + " energize or soothe the constant flow of customers seeking caffeine salvation from their"
        + " daily routines sometimes i wonder what stories these strangers carry with them as they"
        + " order their drinks and disappear back into their lives leaving only the lingering scent"
        + " of vanilla and espresso to mark their brief presence in this small universe of ceramic"
        + " mugs and recycled napkins\n",
    "mathematics has always felt like a foreign language to me despite years of studying equations"
        + " and formulas that supposedly describe the fundamental patterns underlying everything"
        + " from the orbit of planets to the growth of bacteria in petri dishes yet somehow when i"
        + " look at the golden ratio appearing in sunflower seed spirals or fibonacci sequences"
        + " hidden in pinecone structures i sense there might be something beautiful and mysterious"
        + " happening beneath the surface of all those numbers and symbols that once seemed so"
        + " intimidating in high school algebra class where i spent most of my time staring out"
        + " windows and wondering if anyone actually understood what the teacher was talking about"
        + " when she drew parabolas on the blackboard and explained how they related to thrown"
        + " baseballs and satellite dishes the funny thing is that now as an adult i find myself"
        + " drawn to books about quantum physics and chaos theory not because i understand the"
        + " mathematics involved but because the ideas themselves seem to point toward truths about"
        + " reality that are both logical and completely bizarre like the possibility that"
        + " particles can exist in multiple states simultaneously until someone observes them or"
        + " that tiny changes in initial conditions can lead to dramatically different outcomes in"
        + " complex systems which makes me think about how my own life might have unfolded"
        + " differently if i had turned left instead of right on that tuesday morning in march when"
        + " i decided to take a different route to work and ended up meeting the person who would"
        + " later become my closest friend\n",
    "vintage photographs have a way of making the past seem both more real and more distant than it"
        + " actually was especially those old black and white family portraits where everyone looks"
        + " stern and formal because they had to hold still for so long while the camera captured"
        + " their images on glass plates or early film the faces staring back from those frames"
        + " seem to carry the weight of their entire era compressed into a single frozen moment"
        + " that we can now examine from our comfortable distance of decades or centuries wondering"
        + " what they were thinking about as they posed in their best clothes in front of painted"
        + " backdrops or beside ornate furniture that probably represented their most valuable"
        + " possessions i inherited a box of such photographs from my grandmother including images"
        + " of relatives whose names have been lost to time but whose eyes still seem to follow me"
        + " around the room when i spread the pictures across my kitchen table trying to piece"
        + " together the fragments of family history that survived the moves and divorces and"
        + " deaths that scattered our collective memory to the winds some of the photographs show"
        + " children playing in yards that no longer exist in front of houses that were torn down"
        + " decades ago to make room for strip malls and parking lots while others capture moments"
        + " of celebration or mourning that once seemed monumentally important to the people"
        + " involved but now exist only as visual echoes in fading silver halide crystals\n",
    "the abandoned warehouse on the edge of town has been slowly collapsing for fifteen years now"
        + " ever since the manufacturing company that built it moved their operations overseas"
        + " leaving behind a shell of rusted metal and broken windows that now serves as an"
        + " unofficial monument to economic forces beyond anyones control weeds grow through cracks"
        + " in the concrete loading dock where trucks once delivered raw materials and carried away"
        + " finished products destined for stores across the midwest the security fence that once"
        + " surrounded the property has gaps torn in it by vandals or maybe just by time and"
        + " weather allowing urban explorers and graffiti artists to claim the interior walls as"
        + " canvases for their commentary on society and politics and love and loss spelled out in"
        + " spray paint colors that glow under streetlights when darkness falls over the industrial"
        + " district that has become a graveyard for dreams and ambitions that once seemed so solid"
        + " and permanent to the workers who spent their days inside those walls breathing air that"
        + " smelled of machine oil and possibility before the global economy shifted beneath their"
        + " feet like tectonic plates rearranging themselves according to laws of supply and demand"
        + " that care nothing for human attachment to place or purpose yet somehow nature has begun"
        + " to reclaim the space sending vines through broken windows and birds to nest in the"
        + " rafters where they sing songs that no one hears except the occasional photographer or"
        + " urban explorer who comes to document the slow motion transformation of industry into"
        + " wilderness\n",
  };
}
